# Generated by Django 4.0.5 on 2022-07-03 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import home.softDelete
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('bg', 'beginner'), ('ad', 'advanced'), ('ex', 'expert')], max_length=255)),
                ('test_case', models.JSONField()),
                ('test_result', models.JSONField()),
                ('language', models.CharField(max_length=255)),
                ('lecturer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', home.softDelete.SoftDeleteManager()),
            ],
        ),
    ]